ARG PROJECT_HUB=norlabulaval
ARG BASE_IMAGE=libpointmatcher-dependencies
ARG BASE_IMAGE_TAG
FROM ${PROJECT_HUB}/${BASE_IMAGE}:${BASE_IMAGE_TAG:?err} AS libpointmatcher-dependencies

LABEL org.opencontainers.image.authors="luc.coupal.1@ulaval.ca"

ARG LIBPOINTMATCHER_VERSION='head'
ENV LIBPOINTMATCHER_VERSION=${LIBPOINTMATCHER_VERSION}
LABEL libpointmatcher.version="${LIBPOINTMATCHER_VERSION}"

ARG LIBPOINTMATCHER_INSTALL_SCRIPT_FLAG='--build-system-CI-install --compile-test'

ARG LPM_INSTALLED_LIBRARIES_PATH
ARG LPM_LIBPOINTMATCHER_SRC_REPO_NAME
ENV LPM_INSTALLED_LIBRARIES_PATH=${LPM_INSTALLED_LIBRARIES_PATH:?'Build argument needs to be set and non-empty.'}
ENV LPM_LIBPOINTMATCHER_SRC_REPO_NAME=${LPM_LIBPOINTMATCHER_SRC_REPO_NAME:?'Build argument needs to be set and non-empty.'}


SHELL ["/bin/bash", "-c"]
ARG DEBIAN_FRONTEND=noninteractive

# ====Install Libpointmatcher=======================================================================================
WORKDIR "${LPM_INSTALLED_LIBRARIES_PATH}/${LPM_LIBPOINTMATCHER_SRC_REPO_NAME}"

# Copy all files from the checkout branch in the repository (except those in the .dockerignore)
COPY . .

WORKDIR ./build_system/ubuntu

RUN chmod +x entrypoint.bash

# ==== Build libpointmatcher checkout branch ======================================================================
ENV LIBPOINTMATCHER_INSTALL_SCRIPT_FLAG=${LIBPOINTMATCHER_INSTALL_SCRIPT_FLAG}

RUN chmod +x lpm_install_libpointmatcher_ubuntu.bash
RUN bash lpm_install_libpointmatcher_ubuntu.bash \
    --libpointmatcher-version ${LIBPOINTMATCHER_VERSION} \
    ${LIBPOINTMATCHER_INSTALL_SCRIPT_FLAG}

# ==== Execute libpointmatcher unit-test===========================================================================
WORKDIR "${LPM_INSTALLED_LIBRARIES_PATH}/${LPM_LIBPOINTMATCHER_SRC_REPO_NAME}/build"
RUN chmod +x utest/utest
RUN utest/utest --path "${LPM_INSTALLED_LIBRARIES_PATH}/${LPM_LIBPOINTMATCHER_SRC_REPO_NAME}/examples/data/"

# ====End==========================================================================================================
ENTRYPOINT [ "./entrypoint.bash" ]
CMD [ "bash" ]
