#ifndef PYTHON_POINTMATCHERSUPPORT_REGISTRARS_DATAPOINTSFILTER_REGISTRAR_H
#define PYTHON_POINTMATCHERSUPPORT_REGISTRARS_DATAPOINTSFILTER_REGISTRAR_H

#include "pypointmatcher_helper.h"

namespace pointmatcher
{
	void pybindDataPointsFilterRegistrar(py::module& p_module);
}

#endif //PYTHON_POINTMATCHERSUPPORT_REGISTRARS_DATAPOINTSFILTER_REGISTRAR_H
