#ifndef PYTHON_POINTMATCHERSUPPORT_REGISTRARS_ERROR_MINIMIZER_REGISTRAR_H
#define PYTHON_POINTMATCHERSUPPORT_REGISTRARS_ERROR_MINIMIZER_REGISTRAR_H

#include "pypoint_matcher_helper.h"

namespace pointmatcher
{
	void pybindErrorMinimizerRegistrar(py::module& p_module);
}

#endif //PYTHON_POINTMATCHERSUPPORT_REGISTRARS_ERROR_MINIMIZER_REGISTRAR_H
