#ifndef PYTHON_POINTMATCHERSUPPORT_REGISTRARS_ERRORMINIMIZER_REGISTRAR_H
#define PYTHON_POINTMATCHERSUPPORT_REGISTRARS_ERRORMINIMIZER_REGISTRAR_H

#include "pypointmatcher_helper.h"

namespace pointmatcher
{
	void pybindErrorMinimizerRegistrar(py::module& p_module);
}

#endif //PYTHON_POINTMATCHERSUPPORT_REGISTRARS_ERRORMINIMIZER_REGISTRAR_H
