#ifndef PYTHON_POINTMATCHERSUPPORT_REGISTRARS_OUTLIER_FILTER_REGISTRAR_H
#define PYTHON_POINTMATCHERSUPPORT_REGISTRARS_OUTLIER_FILTER_REGISTRAR_H

#include "pypoint_matcher_helper.h"

namespace pointmatcher
{
	void pybindOutlierFilterRegistrar(py::module& p_module);
}

#endif //PYTHON_POINTMATCHERSUPPORT_REGISTRARS_OUTLIER_FILTER_REGISTRAR_H
