readingDataPointsFilters:
  - IdentityDataPointsFilter:

referenceDataPointsFilters:
  - SamplingSurfaceNormalDataPointsFilter:
      knn: 10
      ratio: 1.0 
      samplingMethod: 0
      averageExistingDescriptors: 0

matcher:
  KDTreeMatcher:
    knn: 1
    epsilon: 0 

outlierFilters:
  - TrimmedDistOutlierFilter:
      ratio: 1.0

errorMinimizer:
  PointToPlaneErrorMinimizer

transformationCheckers:
  - CounterTransformationChecker:
      maxIterationCount: 40
  - DifferentialTransformationChecker:
      minDiffRotErr: 0.001
      minDiffTransErr: 0.01
      smoothLength: 4   
      
inspector:
  NullInspector
#  VTKFileInspector

logger:
  NullLogger
#  FileLogger

